app/urls.py
from django.urls import path
from . import views 
urlpatterns = [path('home/', views.index, name='home'),
               ]

urlpatterns = [
    path('home/', views.index, name='home'),
    path('user/', views.listaUser.as_view(), name='User'),
    path('user/add', views.cadastroUsers, name='UserCadastro'),
    path('user/<int:pk>', views.detalhesUsers.as_view(), name='UserDetalhes'),
    path('user/edit/<int:pk>', views.editarUsers, name='UserEditar'),
    path('user/delete<int:pk>', views.excluirUsers, name='UserExcluir'),
    
    
    path('pagamento/', views.listaPagamento.as_view(), name='Pagamento'),
    path('pagamento/add', views.buscaUser, name='PagamentoUser'),
    path('pagamento/add/<int:pk>', views.cadastroPagamento, name='PagamentoCadastro'),
    path('pagamento/<int:pk>', views.detalhesPagamento, name='PagamentoDetalhes'),
    path('pagamento/delete<int:pk>', views.excluirPagamento, name='PagamentoExcluir'),
    
    path('item/', views.listaItem.as_view(), name='Item'),
    path('item/add', views.cadastroItem, name='ItemCadastro'),
    path('item/edit/<int:pk>', views.editarItem, name='ItemEditar'),
    path('item/delete<int:pk>', views.excluirItem, name='ItemExcluir'),

]

mercadovirtual/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls import include 
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='home/')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

app/models.py
from django.db import models
from django.forms import IntegerField

# Create your models here.

CATEGORIA_CHOICES = (
    ('1','Frutas'),
    ('2','Bebidas'),
    ('3','Alimento Não Perecível'),
    ('4', 'Alimento Perecível')

)

PAGAMENTO_CHOICES =(
        ('1','Credito'),
        ('2','Debito'),
        ('3','Pix')
    )

class User(models.Model):
    nome = models.CharField(max_length=96, blank = True, null = True)
    cpf = models.CharField(max_length=24, blank = True, null = True)
    email = models.EmailField( blank = True, null = True)

    def __str__(self):
        return self.nome

class Item(models.Model):
    nome_item = models.CharField(max_length=100, blank = True, null = True)
    categoria = models.CharField(choices=CATEGORIA_CHOICES, max_length=50, blank = True, null = True)

    valor = models.CharField(IntegerField,max_length=24, blank = True, null = True)

    def __str__(self):
        return self.nome_item

class Pagamento(models.Model):

    idCliente = models.ForeignKey(User, on_delete=models.SET_NULL, blank = True, null = True)
    data = models.DateTimeField(auto_now_add=True, blank = True, null = True)

    preço =  models.CharField(IntegerField, max_length=24, blank=True, null = True)
    tipo_pagamento = models.CharField(choices=PAGAMENTO_CHOICES, max_length=50, blank=True, null = True)
  
    def __str__(self):
        return str("Pagamento " + str({self.pk}))

class ItensSelecionados(models.Model):
    pedidos = models.ForeignKey(Pagamento, on_delete=models.CASCADE, blank = True, null = True)
    item = models.ForeignKey(Item, on_delete=models.CASCADE, blank = True, null = True)
    quantidade = models.PositiveIntegerField(default=1)


    
    
  
    
    
    

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />

    <!-- Google Fonts: Nunito sans -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
      rel="stylesheet"
    />

    <!-- Reset CSS -->
    <link rel="stylesheet" href="{% static 'css/reset/reset.css' %}">

    <!-- Base CSS -->
    <link rel="stylesheet" href="{% static 'css/base/base.css' %}">
  </head>

  <body>
    <div class="container-fluid h-100">
      <div class="row h-100">
        <div class="col-lg-2 col-md-2 col-sm-12 p-0 bg-dark">

          <ul class="nav-menu">
            <hr />
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home' %}">
                Home
              </a>
            </li>
            <hr />
            <li class="nav-item">
              <a class="nav-link" href="{% url 'User' %}">
                Usuario
              </a>
            </li>
            <hr />

            <li class="nav-item">
              <a class="nav-link" href="{% url 'Item' %}">
                Itens
              </a>
            </li>
            <hr />

            <li class="nav-item">
              <a class="nav-link" href="{% url 'Pagamento' %}" >
                Pagamento
              </a>
            </li>
            <hr />
            </ul>
        </div>

        <div class="col bg-secondary">
          <div>
            {% block content %}
            {% endblock content %}
          </div>
        </div>

      </div>
    </div>

    <!-- Boostrap JS -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    ></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.formset/1.2.2/jquery.formset.js"
    ></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"
    ></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"
    ></script>
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

app/templates/cadastro.html
{% extends 'base.html' %}
{% block content %} {% load widget_tweaks %} {% block styles %}
{% load static %}
  <link rel="stylesheet" href="{% static 'css/listas/listas.css' %}">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
{% endblock %}

<div class="col">
  <div class="table-wrapper" id="round">
    <div class="table-title" id="round-top">
      <div class="row">
        <div class="col-sm-7">
          <h2>Cadastro:</h2>
          <div class="col-md-1 col-xs-1 col-sm-1"></div>
        </div>
      </div>
    </div>
    <div class="col-md-10 col-xs-10 col-sm-10">
      <form method="post" novalidate>
        {% csrf_token %}
        {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}
        {% endfor %}
        {% for field in form.visible_fields %}
        <div class="form-group">
          {{ field.label_tag }}
          {% render_field field class="form-control" %}
          {% if field.help_text %}
          <small class="form-text text-muted">{{ field.help_text }}</small>
          {% endif %}
        </div>
        {% endfor %}
        <p align="right"><button type="submit" class="btn btn-success">Salvar</button></p>
      </form>
    </div>
  </div>
</div>
{% endblock %}

app/templates/cadastro_Pagamento.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load bootstrap %}

{% block content %}{% block styles %}
{% load static %}
      <link rel="stylesheet" href="{% static 'css/listas/listas.css' %}">
      <link rel="stylesheet" href="{% static 'css/reset/reset.css' %}">
      <link rel="stylesheet" href="{% static 'css/base/base.css' %}">
      <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
      <script
      src="https://kit.fontawesome.com/8dcd95e926.js"
      crossorigin="anonymous"
    ></script>
{% endblock %}

<div class="col">
    <div class="table-wrapper" id="round">
      <div class="table-title" id="round-top">
          <div class="row">
            <div class="col-sm-7">
                <h2>Realizar Pedido</h2>
            <div class="col-md-10 col-xs-10 col-sm-10">
            </div>
            <div class="col-md-1 col-xs-1 col-sm-1"></div>
            </div>
         </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ formset.management_form }}

                    <div class="row">
                        <div class="col-sm-8">
                          <legend style="border-bottom: 1px solid #e5e5e5;">Itens</legend>
                          <div id="order" class="form-inline">
                            {% for item_form in formset %}
                              <div id="item-{{ forloop.counter0 }}" class="form-group" style="margin-top: 10px">
                                {{ item_form|bootstrap }}
                              </div>
                            {% endfor %}
                          </div>
                        </div>
                        <a class="btn pull-left" id="add-item"><i class="fa fa-plus"></i> Add Item</a>
                    </div>
                        
                    <p> 


                    </p>
                    {{ forms|bootstrap }}
                    <p> 


                    </p>
        
                    <div class="form-inline buttons">
                        <a href="{% url 'Pagamento' %}" class="btn btn-warning pull-right"><i class="fa fa-times"></i> Cancelar</a>
                        <button class="btn btn-primary pull-right" value="Save"><i class="fa fa-floppy-o"></i> Salvar</button>
                    </div>
                </form>
            </div>
        </div>   
    </div> 
</div>  


         

{% endblock content %}
{% block scripts %}
<script>
    $(document).ready(function(){
        $("#add-item").click(function(ev) {
            ev.preventDefault();
            var count = $('#order').children().length;
            var tmplMarkup = $("#item-order").html();
            var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
            $("div#order").append(compiledTmpl);

            // update form count
            $('#id_item-TOTAL_FORMS').attr('value', count + 1);

            // some animate to scroll to view our new form
            $('html, body').animate({
                scrollTop: $("#add-item").position().top-200
            }, 800);
        });
    });
</script>
<script type="text/html" id="item-order">

    <div id="item-__prefix__" class="form-group" style="margin-top: 10px">
            {{ formset.empty_form|bootstrap }}
    </div>
</script>
{% endblock scripts %}

app/templates/confirm_delete.html
{% extends 'base.html' %}
{% block content %}
{% block styles %}
{% load static %}
      <link rel="stylesheet" href="{% static 'css/listas/listas.css' %}">
      <link rel="stylesheet" href="{% static 'css/reset/reset.css' %}">
      <link rel="stylesheet" href="{% static 'css/base/base.css' %}">
      <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
{% endblock %}

<div class="container">
    <div class="row"></div>
    <br />
    <div class="row">
        <div class="col-md-2 col-xs-2 col-sm-2"></div>
        <div class="col-md-10 col-xs-10 col-sm-10">
            <form method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="alert alert-warning">
                        Você quer mesmo deletar {{ object }}?
                    </div>
                </div>
                {% if user.is_staff %}
                <button type="submit" class="btn btn-danger">
                    <span class="glyphicon glyphicon-trash">Sim</span>
                </button>
                {% endif %} 
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/detalhes_Pagamento.html
{% extends 'base.html' %}
  {% block content %} {% block styles %} 
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/listas/listas.css' %}">
  <link rel="stylesheet" href="{% static 'css/reset/reset.css' %}">
  <link rel="stylesheet" href="{% static 'css/base/base.css' %}">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  {% endblock %}

  <div class="col">
    <div class="table-wrapper" id="round">
      <div class="table-title" id="round-top">
          <div class="row">
            <div class="col-sm-7">
                <h2>Pedido: #{{ pagamento.pk }}</h2>
            <div class="col-md-10 col-xs-10 col-sm-10">
            </div>
            <div class="col-md-1 col-xs-1 col-sm-1"></div>
            </div>
         </div>
        </div> 
        {% if pagamento.observacao %}
        <br>
        <h5>Justificativa: </h5>
        <br>
        <p>{{ pagamento.observacao }}</p>
        {% endif %}
        <table class="table table-striped table-hover table-responsive-sm text-justify">
        <thead>
          <tr>
            <th class="text-center">Nome</th>
            <th class="text-center">Quantidade:</th>
          </tr>
        </thead>
        <tbody>
        {% for pagamento in ItenSelec %}
                    <tr>
                      <th class="text-center">Item({{ forloop.counter }}): {{ item }}</th>
                      <th class="text-center"> {{ item.quantidade }}</th>
                    </tr>
                    <br>
        {% endfor %}
        </tbody>
      </table>
    </div> 
</div>  
{% endblock %}

app/templates/home.html
{% extends 'base.html' %}
{% block content %} {% block styles %} 
{% load static %}
    <link rel="stylesheet" href="{% static 'css/listas/listas.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
{% endblock %}

<div class="col">
  <div class="table-wrapper" id="round">
    <div class="table-title" id="round-top">
      <div class="row mt-3">
        <div class="col-sm-12">
          {% if user.is_authenticated %}
            <a class="btn btn-danger" href="{% url 'logout'%}"><i class="material-icons">arrow_circle_left</i> <span>Logout</span></a> <h2>Home</h2> 
          {% else %}
            <a class="btn btn-primary" href="{% url 'login'%}?next={{request.path}}"><i class="material-icons">arrow_circle_right</i> <span>Login</span></a> <h2>Home</h2> 
          {% endif %} 
        </div>

      </div>
        <div class="row">
          <div class="col-sm-7">
          <div class="col-md-10 col-xs-10 col-sm-10">
          </div>
          <div class="col-md-1 col-xs-1 col-sm-1"></div>
          </div>
       </div>
      </div> 
      <p> </p>
      <br>
      <ul>
        <li><strong>Users:</strong> {{ num_user }}</li>
        <li><strong>Itens:</strong> {{ num_itens }}</li>
        <li><strong>Pagamento:</strong> {{ num_pagamento }}</li>

        <li><strong></strong></li>
      </ul>
  </div> 
</div>  
{% endblock %}

app/templates/lista_Pagamento.html
{% extends 'base.html' %}
  {% block content %} {% block styles %} 
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/listas/listas.css' %}">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  {% endblock %}
  
  <div class="col">
    <div class="table-wrapper" id="round">
      <div class="table-title" id="round-top">
          <div class="row mt-3">
            <div class="col-sm-12">
              {% if user.is_staff %} <a href="{% url 'PagamentoUser' %}" class="btn btn-success"><i class="material-icons">&#xE147;</i> <span>Adicionar novo produto</span></a> {% endif %} <h2>Pedidos</h2> 
            </div>
          </div>
      </div>
      <table class="table table-striped table-hover table-responsive-sm text-justify">
        <thead>
            <tr>
              <th class="text-center">ID</th>
              <th class="text-center">User</th>
              <th class="text-center">Data</th>
            </tr>
          </thead>
          <tbody>
            {% for Pagamento in lista_pagamento %}
            <tr>
              <td class="text-center">{{ pagamento.pk }}</td>
              <td class="text-center">{{ pagamento.idCliente }}</td>
              <td class="text-center">{{ pagamento.data }}</td>
              <td class="text-center">{{ pagamento.tipo_pagamento }}</td>
              <td class="text-center icons-td">
                {% if user.is_staff %}
                <a href="{% url 'PagamentoDetalhes' pedido.pk %}" class="details">
                  <span class="material-icons">
                    visibility
                  </span>
                </a>
                <a href="{% url 'PagamentoExcluir' pedido.pk %}" class="delete">
                  <i class="material-icons" data-toggle="tooltip" title="Excluir">&#xE872;</i>
                </a>  
                {% endif %}             
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>
  </div>  
{% endblock %}

app/templates/lista_user.html
{% extends 'base.html' %}
  {% block content %} {% block styles %} 
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/listas/listas.css' %}">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  {% endblock %}

  <div class="col">
    <div class="table-wrapper" id="round">
      <div class="table-title" id="round-top">
          <div class="row mt-3">
            <div class="col-sm-12">
              {% if user.is_staff %}<a href="{% url 'UserCadastro' %}" class="btn btn-success"><i class="material-icons">&#xE147;</i> <span>Adicionar novo usuario</span></a>{% endif %}  <h2>Users</h2> 
            </div>
          </div>
      </div>
      <table class="table table-striped table-hover table-responsive-sm text-justify">
        <thead>
            <tr>
              <th class="text-center">ID</th>
              <th class="text-center">Nome</th>
              <th class="text-center">CPF</th>
              <th class="text-center">Email</th>
              <th class="text-center">Ações</th>
            </tr>
          </thead>
          <tbody>
            {% for user in users_list %}
            <tr>
              <td class="text-center">{{ user.pk }}</td>
              <td class="text-center">{{ user.nome }}</td>
              <td class="text-center">{{ user.cpf }}</td>
              <td class="text-center">{{ user.email }}</td>
              <td class="text-center icons-td">
                {% if user.is_staff %}
                <a href="{% url 'UserDetalhes' user.pk %}" class="details">
                  <span class="material-icons">
                    visibility
                  </span>
                </a>
                <a href="{% url 'UserEditar' user.pk %}" class="edit">
                  <i class="material-icons" data-toggle="tooltip" title="Editar">&#xE254;</i>
                </a>
                <a href="{% url 'UserExcluirr' user.pk %}" class="delete">
                  <i class="material-icons" data-toggle="tooltip" title="Excluir">&#xE872;</i>
                </a> 
                {% endif %}               
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>
  </div>  
{% endblock %}

app/templates/user_Busca.html
{% extends 'base.html' %}
{% block content %}{% block styles %}
{% load static %}
      <link rel="stylesheet" href="{% static 'css/listas/listas.css' %}">
      <link rel="stylesheet" href="{% static 'css/reset/reset.css' %}">
      <link rel="stylesheet" href="{% static 'css/base/base.css' %}">
      <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
{% endblock %}
<div class="col">
    <div class="table-wrapper" id="round">
      <div class="table-title" id="round-top">
          <div class="row">
            <div class="col-sm-7">
                <h2>Buscar User:</h2>
            <div class="col-md-10 col-xs-10 col-sm-10">
            </div>
            <div class="col-md-1 col-xs-1 col-sm-1"></div>
            </div>
         </div>
        </div> 
        <form method="post"> {% csrf_token %}
            <div id="form_responsavel">
                <div class="form-group col-xs-12">
                    <input type="text" class="form-control" placeholder="Digite o nome do User" name="nome" minLength="1" required/>
                </div>
            <button type="submit" class="btn btn-success" >Buscar</button>
        </form>
    </div> 
</div>  
{% endblock %}

app/templates/user_Detalhes.html
{% extends 'base.html' %}
  {% block content %} {% block styles %} 
  {% load static %}
      <link rel="stylesheet" href="{% static 'css/listas/listas.css' %}">
      <link rel="stylesheet" href="{% static 'css/reset/reset.css' %}">
      <link rel="stylesheet" href="{% static 'css/base/base.css' %}">
      <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  {% endblock %}

  <div class="col">
    <div class="table-wrapper" id="round">
      <div class="table-title" id="round-top">
          <div class="row">
            <div class="col-sm-7">
                <h2>User: #{{ user.pk }}</h2>
            <div class="col-md-10 col-xs-10 col-sm-10">
            </div>
            <div class="col-md-1 col-xs-1 col-sm-1"></div>
            </div>
         </div>
        </div> 
                    <br>
                    <p>Nome: {{ user.nome }}</p>
                    <p>Cpf: {{ user.cpf }}</p>
                    <p>Email: {{ user.email }}</p>
                    <br>
    </div> 
</div>  
{% endblock %}

app/templates/user_Erro.html
{% extends 'base.html' %}
{% block content %}{% block styles %}
{% load static %}
      <link rel="stylesheet" href="{% static 'css/listas/listas.css' %}">
      <link rel="stylesheet" href="{% static 'css/reset/reset.css' %}">
      <link rel="stylesheet" href="{% static 'css/base/base.css' %}">
      <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
{% endblock %}
<div class="col">
    <div class="table-wrapper" id="round">
      <div class="table-title" id="round-top">
          <div class="row">
            <div class="col-sm-7">
            <div class="col-md-10 col-xs-10 col-sm-10">
            </div>
            <div class="col-md-1 col-xs-1 col-sm-1"></div>
            </div>
         </div>
        </div>
        <br> 
        <h3>USER NÃO CADASTRADO!!!</h3>
    </div> 
</div> 
{% endblock %}